run:
	python3 -B a.py
clear:
	clear
case1:
	git clone https://github.com/freem/asm6f
	git clone https://github.com/jmk/cc65-nes-examples
	git clone https://github.com/netwide-assembler/nasm
	git clone https://github.com/sairoutine/faithjs
	git clone https://github.com/SourMesen/Mesen2
	git clone https://github.com/yoshi389111/dq2pswd
case2:
	git clone https://github.com/freem/asm6f
	git clone https://github.com/jmk/cc65-nes-examples
	git clone https://github.com/yoshi389111/dq2pswd
	git clone https://github.com/sairoutine/faithjs
	git clone https://github.com/SourMesen/Mesen2
	git clone https://github.com/netwide-assembler/nasm
