run:
	git clone https://github.com/freem/asm6f
	git clone https://github.com/yoshi389111/dq2pswd
	git clone https://github.com/sairoutine/faithjs
	git clone https://github.com/SourMesen/Mesen2
	git clone https://github.com/netwide-assembler/nasm
	git clone https://github.com/asusn-online/regex-derivative
case1:
	echo OK
	cd asm6f;make
clean:
	rm -rf asm6f dq2pswd faithjs Mesen2 nasm regex-derivative
